FROM python:3.9.15-slim-buster

RUN mkdir /app

WORKDIR /app

RUN mkdir NumPalabras

RUN touch NumPalabra/numPalabra.csv


COPY . /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["python", "lisa2.py"]
